### ISSUE TITLE
Build fails with newest version of @reactivex/rxjs

### ISSUE THREAD

**Issue by eanders-MS** [billba/botchat#100]
If you npm install it will grab the latest @reactivex/rxjs (5.0.0-rc.1), which is newer than what is specified in package.json (5.0.0-beta.12). The versions are different enough to break the BotChat build. We should update BotChat to work with the newer library, or pin the library version number.

**Comment by billba** [comment]
I’ll do that right now.

**Comment by billba** [comment]
.rc1 breaks us, but they've fixed that bug, so my solution right now is to freeze us at beta-12
