### ISSUE TITLE
Filename casing issue breaking Emulator on Ubuntu

### ISSUE THREAD

**Issue by eanders-MS** [billba/botchat#110]
This line in BotChat.ts is causing a module load failure on Linux systems:
`export { SecretOrToken, DirectLine } from './directLine';`
Upper-casing to `'./DirectLine'` fixes the problem.

**Comment by billba** [comment]
But the actual file is ./directLine! Can you check to make sure that's true? I'm wondering if my case-sensitivity adventure broke something.

**Comment by eanders-MS** [comment]
Weird. It is upper case in my branch, but lower in yours. I'll fix it over there!

**Comment by billba** [comment]
For the record it's supposed to be lower case.
