### ISSUE TITLE
Potential nullrefs in long property accessors

### ISSUE THREAD

**Issue by danmarshall** [billba/botchat#122]
I've run into this once and I expect we may see it again, with an accessor like ```attachment.content.image.url``` where ```attachment.content.image``` is null. Perhaps we just solve it on a case-by-case basis, but just wanted to bring it up.

**Comment by danmarshall** [comment]
Maybe the real issue is that the chat seems to stop working when a nullref is encountered. The error is:
_botchat.js:334 Uncaught TypeError: Cannot read property 'scrollTop' of null_
Then the chat stops responding.

**Comment by billba** [comment]
related to #63

**Comment by billba** [comment]
Yes, the issue is that we fail on imperfect input. We need to harden against this stuff.

**Comment by billba** [comment]
I fixed as many of these as I could find. Mostly we need more test cases.
