### ISSUE TITLE
Carousel nav causes scroll to bottom of chat window

### ISSUE THREAD

**Issue by eanders-MS** [billba/botchat#22]
After a carousel is displayed and then a few more messages are sent and received, if I scroll up to the carousel and navigate it left or right, after clicking on the nav button the chat window scrolls to the bottom (autoscroll, presumably).

See video: https://kodu.blob.core.windows.net/kodu/eanders/capture-2.mp4

**Comment by billba** [comment]
No longer happening since the Redux rewrite, where I touched the autoscroll code quite a bit.
