### ISSUE TITLE
imBack button press appears as message from another user

### ISSUE THREAD

**Issue by eanders-MS** [billba/botchat#23]
The button press for imBack (and possibly postBack also) sends the user's id rather than user's name in the message.from.id field. Unsure which one is correct. Screen capture:
![image](https://cloud.githubusercontent.com/assets/12176807/19089256/64c84722-8a2e-11e6-99d0-0457035091d2.png)

**Comment by billba** [comment]
I'm not sure what you mean by "user's name"... the id is the only way we have to identify the user.

**Comment by eanders-MS** [comment]
When we send a text message, we set the from.id field to 'user':
`from: {id: 'user'},`
But when we send the button ImBack message, we set it to the user's id:
`from: {id: this.state.userId},`

I believe this is causing the imBack message to be incorrectly identified as not from the user. Here's the code that makes this decision (from History.tsx):
`<div className={ 'wc-message wc-message-from-' + (activity.from.id === 'user' ? 'me' : 'bot') }>`

**Comment by billba** [comment]
In this case the imBack message is actually doing the right thing. I introduced a regression when I did the big Activity refactoring. Fixing now.
