### ISSUE TITLE
Tokens not refreshed

### ISSUE THREAD

**Issue by billba** [billba/botchat#28]
We aren't refreshing tokens, so after about 30 minutes the connection to the bot fails.

**Comment by danmarshall** [comment]
We just encountered this issue again, so I re-opened to track it. Does it have something to do with the fact that I am creating a DirectLine3 outside of the BotChat? (I'm doing it the way it's done in public/index.html)

**Comment by billba** [comment]
No. I can't reproduce this. Are you sure it's an expired token versus some other Ajax error?
Can you provide more details? Is the DL being started with a secret or with a token?

**Comment by billba** [comment]
Found and fixed for reals now.
