### ISSUE TITLE
Cards cropped on narrow display

### ISSUE THREAD

**Issue by billba** [billba/botchat#46]
We can expect the web control to be housed in fairly narrow iframes (not to mention mobile displays) and right now at width=300 all the cards are cropped. Obviously there will be a minimum width below which we can make no guarantees, so let's decide what that is and code the CSS accordingly.

**Comment by danmarshall** [comment]
In our design group we've been using iPhone4 as the minimum device width which is 320 wide.

**Comment by billba** [comment]
Even at width=320 things are cropped pretty badly.

Do we have any info on how the current WebChat (and other similar bot chats) are being deployed? By coincidence (OR IS IT?) the "Ask Jenn" bot on alaskaair.com is exactly 320 pixels wide.

**Comment by danmarshall** [comment]
Closing this issue. yay! @billba can you deploy a new demo build?
