### ISSUE TITLE
How shall we handle localized text?

### ISSUE THREAD

**Issue by billba** [billba/botchat#49]
Where should the text sit?
How shall we decide which is the current locale?

**Comment by billba** [comment]
For now locale is passed in as a prop to the App/Chat. If it's not passed, we take the browser locale. If that's undefined (older browsers), we use 'en-us'. We have a list of strings-per-locale, and we do our best to match the requested locale to whatever is currently supported.

**Comment by didaskein** [comment]
Hi, 

I think there are a bug for Local detection. Local Is set with Emulator but always null when using channels (Mail, FB, Teams,...)

I have changed the local settings of Chrome : chrome://chrome/settings/languages   -> Only French
![image](https://cloud.githubusercontent.com/assets/13362276/21728357/1a49a72e-d446-11e6-81e7-cfaee136b517.png)

The code to show the local send by the channel : it is null for Web, Facebook, Skype… I think there is a problem….
I’m ok for no local with Mail, but I’m not ok for Web, FB, Skype…

![image](https://cloud.githubusercontent.com/assets/13362276/21728307/d6b2b082-d445-11e6-9cf9-f30993aee368.png)

![image](https://cloud.githubusercontent.com/assets/13362276/21728326/eccafe4c-d445-11e6-9e9f-d7e4c2c2145d.png)

Thank in advance,

**Comment by danmarshall** [comment]
We don't currently have French translations in our [string table](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Strings.ts) but it would be great if you can add them and send a pull request @didaskein :)

**Comment by billba** [comment]
I think the point that @didaskein is making is that WebChat does not send the locale up to the bot, which is true and has nothing to do with the string table.

**Comment by billba** [comment]
I filed and resolved issue #263.
