### ISSUE TITLE
History.autoscrollSubscription might be undefined

### ISSUE THREAD

**Issue by hailiu2586** [billba/botchat#78]
this.autoscrollSubscription might be undefined.

	    History.prototype.componentWillUnmount = function () {
	        this.autoscrollSubscription.unsubscribe();
	        this.storeUnsubscribe();
	    };

**Comment by hailiu2586** [comment]
looks like 
	    History.prototype.componentDidMount = function () {
	        **var** autoscrollSubscription = rxjs_1.Observable
	            .fromEvent(this.scrollMe, 'scroll')
	            .map(function (e) { return e.target.scrollTop + e.target.offsetHeight >= e.target.scrollHeight; })
	            .distinctUntilChanged()
	            .subscribe(function (autoscroll) {
	            return Store_1.getStore().dispatch({ type: 'Set_Autoscroll', autoscroll: autoscroll });
	        });
is not setting this.autoscrollSubscription correclty

**Comment by eanders-MS** [comment]
Opps, my bug. Will fix today.

Sent from ?

On Oct 26, 2016, at 12:26 PM, Hai Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


looks like
History.prototype.componentDidMount = function () {
var autoscrollSubscription = rxjs_1.Observable
.fromEvent(this.scrollMe, 'scroll')
.map(function (e) { return e.target.scrollTop + e.target.offsetHeight >= e.target.scrollHeight; })
.distinctUntilChanged()
.subscribe(function (autoscroll) {
return Store_1.getStore().dispatch({ type: 'Set_Autoscroll', autoscroll: autoscroll });
});
is not setting this.autoscrollSubscription correclty

-
