### ISSUE TITLE
Polling / watermark behavior causing duplicate rendering

### ISSUE THREAD

**Issue by danmarshall** [billba/botchat#90]
We are seeing duplicate posts appearing in the chat stream. Looking at the network traffic, we may see a response message for a poll request for watermark=7 for example. Then we will see another poll request for watermark=7. The polling "feels" faster - maybe we have 2 polls going? Also to be bulletproof we should only render unique IDs.

**Comment by eanders-MS** [comment]
Hm, Is it possible you have more than one direct line instantiated?

**Comment by billba** [comment]
I haven’t seen this myself but I’ll look into it.

(There is already an issue about de-duping messages with the same ID, but that is a separate question.)

**Comment by billba** [comment]
Ah I bet that’s it. I know what to fix.

**Comment by eanders-MS** [comment]
Since you're passing in the directline instance, its lifetime differs from the chat. I wonder if it is getting duplicated. There may be lingering subscriptions to a previous one.

**Comment by danmarshall** [comment]
My bad - I was creating a DirectLine in the render() pass **yikes!**

**Comment by billba** [comment]
Well this forced me to look at the code and I ended up adding some useful cleanup...
