### ISSUE TITLE
Ability to unload DirectLine objects

### ISSUE THREAD

**Issue by danmarshall** [billba/botchat#92]
Once I instantiate a DirectLine3 object, it remains alive and keeps making http requests. Even if my reference to it goes out of scope, there currently is no way to stop it.

**Comment by billba** [comment]
Yup I’m working on this right now.

**Comment by billba** [comment]
Now BotConnection has start() and end() methods. When you instantiate a DirectLine[3] object, not much happens. It needs to be start()-ed.

Chat calls start() when it is created, and end() on componentWillUnmount(), which should cleanup the DirectLine[3] object to the point where it can be re-start()-ed.

But... this is hard for me to test right now so you'll have to tell me how well it works. Please reopen this if the problem persists.

Also, all this exposes how much the innards of DirectLine[3] are a mess. There is a lot of rxjs cleanup that needs to happen. But for now it works.
